[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "depth_plane_est"
version = "0.0.0"
description = "A short description of your package"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24",
    "open3d",
]
